ALTER TABLE EVALUATION DROP CONSTRAINT FK_EVALUATION_IDUSER
ALTER TABLE EVALUATION DROP CONSTRAINT FK_EVALUATION_IDPRODUCT
ALTER TABLE PRODUCT DROP CONSTRAINT FK_PRODUCT_IDCATEGORY
ALTER TABLE PRODUCT DROP CONSTRAINT FK_PRODUCT_IDBRAND
ALTER TABLE SHOP DROP CONSTRAINT FK_SHOP_IDADDRESS
ALTER TABLE PRODUCTDISCOUNT DROP CONSTRAINT FK_PRODUCTDISCOUNT_IDDISCOUNT
ALTER TABLE PRODUCTDISCOUNT DROP CONSTRAINT FK_PRODUCTDISCOUNT_IDPRODUCT
ALTER TABLE PRODUCTLIST DROP CONSTRAINT FK_PRODUCTLIST_IDLIST
ALTER TABLE PRODUCTLIST DROP CONSTRAINT FK_PRODUCTLIST_IDPRODUCT
ALTER TABLE PRODUCTSHOP DROP CONSTRAINT FK_PRODUCTSHOP_IDSHOP
ALTER TABLE PRODUCTSHOP DROP CONSTRAINT FK_PRODUCTSHOP_IDPRODUCT
DROP TABLE ADDRESS
DROP TABLE BRAND
DROP TABLE DISCOUNT
DROP TABLE EVALUATION
DROP TABLE LIST
DROP TABLE PRODUCT
DROP TABLE SHOP
DROP TABLE USER
DROP TABLE CATEGORY
DROP TABLE PRODUCTDISCOUNT
DROP TABLE PRODUCTLIST
DROP TABLE PRODUCTSHOP
